server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs-alberto
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs-alberto
          __path__: /var/log/alberto/*/*_filtered.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            description: description
      - timestamp:
          source: timestamp
          format: Unix
  - job_name: varlogs-javi
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs-javi
          __path__: /var/log/javi/*/*_filtered.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            description: description
      - timestamp:
          source: timestamp
          format: Unix
